/** Static registry of the 140 integrated capabilities grouped by domain. */

export type DomainId = 'all' | 'life' | 'commerce' | 'finance' | 'devops' | 'marketing' | 'ai' | 'creative'

export interface CapabilityItem {
  readonly id: string
  readonly name: string
  readonly domain: Exclude<DomainId, 'all'>
  readonly description: string
  readonly tools: readonly string[]
  readonly envKey?: string
  readonly samplePrompt: string
}

export const CAPABILITIES: readonly CapabilityItem[] = [
  // --- Domain I: Central Life Management (20) ---
  {
    id: 'calendar',
    name: 'Google & Outlook Calendar',
    domain: 'life',
    description: 'CalDAV, Google, and Outlook calendar synchronization and intelligent scheduling briefings',
    tools: ['calendar_list', 'calendar_create', 'calendar_briefing'],
    envKey: 'GOOGLE_CALENDAR_TOKEN',
    samplePrompt: 'Check my schedule for today and provide a prioritized morning briefing.',
  },
  {
    id: 'health',
    name: 'Apple Health & Oura / Whoop',
    domain: 'life',
    description: 'Wearable biometric telemetry aggregation for sleep, HRV, strain, and recovery tracking',
    tools: ['health_get_metrics', 'health_analyze_recovery'],
    envKey: 'OURA_PERSONAL_ACCESS_TOKEN',
    samplePrompt: 'Analyze my recovery score and sleep metrics from last night to plan today\'s deep work.',
  },
  {
    id: 'finance',
    name: 'Plaid & Personal Banking',
    domain: 'life',
    description: 'Financial API connector for real-time transaction monitoring and budget tracking',
    tools: ['finance_list_transactions', 'finance_get_balances'],
    envKey: 'PLAID_SECRET',
    samplePrompt: 'Review my recent checking and savings transactions and flag unexpected charges.',
  },
  {
    id: 'notes',
    name: 'Obsidian Second Brain',
    domain: 'life',
    description: 'Markdown knowledge base synchronization and automated daily journaling',
    tools: ['notes_search', 'notes_append_journal'],
    envKey: 'OBSIDIAN_VAULT_PATH',
    samplePrompt: 'Search my Obsidian vault for notes on AI agent architectures and summarize key patterns.',
  },
  {
    id: 'home',
    name: 'Home Assistant IoT',
    domain: 'life',
    description: 'Home Assistant integration for ambient environment control and smart home automations',
    tools: ['home_get_state', 'home_call_service'],
    envKey: 'HASS_TOKEN',
    samplePrompt: 'Check the status of my office smart lights and set them to focus mode.',
  },
  {
    id: 'comms',
    name: 'Telegram & Comms Gateway',
    domain: 'life',
    description: 'Unified messaging gateway for asynchronous alerts and bot notifications',
    tools: ['comms_send_message', 'comms_list_unread'],
    envKey: 'TELEGRAM_BOT_TOKEN',
    samplePrompt: 'Send a summary of today\'s accomplishments to my private Telegram channel.',
  },
  {
    id: 'tasks',
    name: 'Todoist & Task Bridge',
    domain: 'life',
    description: 'Task management bridge for centralized task triage and deadline tracking',
    tools: ['tasks_list', 'tasks_create'],
    envKey: 'TODOIST_API_TOKEN',
    samplePrompt: 'List all overdue tasks in Todoist and reschedule them to this afternoon.',
  },
  {
    id: 'media',
    name: 'Pocket & Media Ingest',
    domain: 'life',
    description: 'Reading queue ingestion for automated summarization and learning queues',
    tools: ['media_add_queue', 'media_summarize'],
    envKey: 'POCKET_ACCESS_TOKEN',
    samplePrompt: 'Summarize the top 3 unread articles in my reading queue.',
  },
  {
    id: 'location',
    name: 'Weather & Transit Intelligence',
    domain: 'life',
    description: 'Location context, OpenWeather forecast, and transit commute tracking',
    tools: ['location_get_weather', 'location_calculate_commute'],
    envKey: 'OPENWEATHER_API_KEY',
    samplePrompt: 'What is today\'s weather forecast and expected traffic for my commute?',
  },
  {
    id: 'vault',
    name: '1Password Vault CLI',
    domain: 'life',
    description: 'Secure password manager CLI bridge for credential management and secret audits',
    tools: ['vault_get_secret', 'vault_audit_expiry'],
    envKey: 'OP_SERVICE_ACCOUNT_TOKEN',
    samplePrompt: 'Audit my vault credentials and report any API keys expiring within 30 days.',
  },
  {
    id: 'contacts',
    name: 'Google Contacts & CRM Sync',
    domain: 'life',
    description: 'Personal contact book manager with interaction history and birthday alerts',
    tools: ['contacts_search', 'contacts_update'],
    envKey: 'GOOGLE_CONTACTS_TOKEN',
    samplePrompt: 'Find contact details and recent interactions for John Doe.',
  },
  {
    id: 'groceries',
    name: 'Instacart & Grocery Restock',
    domain: 'life',
    description: 'Smart grocery list tracking with automated replenishment orders',
    tools: ['groceries_get_list', 'groceries_add_item'],
    samplePrompt: 'Review my weekly pantry inventory and draft a grocery restock order.',
  },
  {
    id: 'habits',
    name: 'Habitify & Daily Routines',
    domain: 'life',
    description: 'Habit consistency tracking and behavioral streak analysis',
    tools: ['habits_log_streak', 'habits_get_summary'],
    samplePrompt: 'How consistent have I been with my morning meditation and workout routines this month?',
  },
  {
    id: 'fitness',
    name: 'Strava & Workout Telemetry',
    domain: 'life',
    description: 'Athletic activity logging and performance progression stats',
    tools: ['strava_list_activities', 'strava_get_stats'],
    envKey: 'STRAVA_CLIENT_SECRET',
    samplePrompt: 'Analyze my running mileage and pace improvement over the last 4 weeks.',
  },
  {
    id: 'sleep',
    name: 'Eight Sleep & Climate Pod',
    domain: 'life',
    description: 'Smart bed temperature adjustment and nocturnal heart rate metrics',
    tools: ['sleep_get_stage_data', 'sleep_adjust_temp'],
    samplePrompt: 'Check my sleep quality stages from last night and optimize tonight\'s bed temperature.',
  },
  {
    id: 'medication',
    name: 'Prescription & Supplement Tracker',
    domain: 'life',
    description: 'Daily vitamin schedule and refill reminder service',
    tools: ['med_log_dose', 'med_check_refills'],
    samplePrompt: 'Remind me of my evening supplement stack and check if any need a refill.',
  },
  {
    id: 'travel',
    name: 'TripIt & Flight Tracker',
    domain: 'life',
    description: 'Unified flight, hotel reservation, and itinerary assistant',
    tools: ['travel_get_itinerary', 'travel_check_delays'],
    samplePrompt: 'Check for gate changes or delays on my upcoming flight to San Francisco.',
  },
  {
    id: 'car',
    name: 'Tesla & Smart Vehicle Telemetry',
    domain: 'life',
    description: 'Electric vehicle charge state, cabin preconditioning, and location',
    tools: ['tesla_get_state', 'tesla_set_climate'],
    envKey: 'TESLA_REFRESH_TOKEN',
    samplePrompt: 'Check vehicle battery level and start preheating the cabin.',
  },
  {
    id: 'pet',
    name: 'PetSafe & Smart Feeder',
    domain: 'life',
    description: 'Automated pet feeding schedules and collar activity tracking',
    tools: ['pet_dispense_food', 'pet_get_activity'],
    samplePrompt: 'Dispense the evening pet food portion and verify feeder hopper levels.',
  },
  {
    id: 'journal',
    name: 'Day One & Voice Reflection',
    domain: 'life',
    description: 'Daily voice memo transcription and sentiment reflection log',
    tools: ['journal_create_entry', 'journal_reflect'],
    samplePrompt: 'Create a gratitude journal entry summarizing the positive highlights of today.',
  },

  // --- Domain II: E-Commerce & Arbitrage (20) ---
  {
    id: 'ebay-arbitrage',
    name: 'eBay Deal & Resale Arbitrage',
    domain: 'commerce',
    description: 'Automated search monitoring, sold-price analysis, and bidding for resale margins',
    tools: ['ebay_search_deals', 'ebay_analyze_margin'],
    envKey: 'EBAY_APP_ID',
    samplePrompt: 'Search eBay for undervalued MacBook M2 laptops ending soon and calculate profit margins.',
  },
  {
    id: 'amazon-fba',
    name: 'Amazon FBA & SP-API Bridge',
    domain: 'commerce',
    description: 'Inventory stockout alerts, dynamic repricing, and profit tracking',
    tools: ['amazon_get_inventory', 'amazon_update_price'],
    envKey: 'AMAZON_SP_API_KEY',
    samplePrompt: 'Audit Amazon inventory levels and identify items needing price adjustments to hold Buy Box.',
  },
  {
    id: 'shopify-storefront',
    name: 'Shopify Storefront Manager',
    domain: 'commerce',
    description: '24/7 store management, customer support drafting, and catalog updates',
    tools: ['shopify_list_orders', 'shopify_update_product'],
    envKey: 'SHOPIFY_ACCESS_TOKEN',
    samplePrompt: 'List unfulfilled Shopify orders from the past 24 hours and draft customer support replies.',
  },
  {
    id: 'gumroad',
    name: 'Gumroad & Lemon Squeezy',
    domain: 'commerce',
    description: 'Digital product delivery, license generation, and sales metrics',
    tools: ['gumroad_list_sales', 'gumroad_create_license'],
    envKey: 'GUMROAD_ACCESS_TOKEN',
    samplePrompt: 'Generate a weekly revenue report for digital products sold on Gumroad.',
  },
  {
    id: 'ticketmaster',
    name: 'Ticketmaster & Event Arbitrage',
    domain: 'commerce',
    description: 'Event ticketing price tracking and secondary resale margin calculation',
    tools: ['tickets_search_events', 'tickets_analyze_arbitrage'],
    envKey: 'TICKETMASTER_API_KEY',
    samplePrompt: 'Monitor concert ticket availability and detect underpriced resale seats.',
  },
  {
    id: 'fiverr-upwork',
    name: 'Fiverr & Upwork Gig Prospector',
    domain: 'commerce',
    description: 'Freelance job scanning, automated proposal drafting, and proposal dispatch',
    tools: ['freelance_scan_jobs', 'freelance_draft_proposal'],
    samplePrompt: 'Scan Upwork for TypeScript agent development postings and draft tailored proposals.',
  },
  {
    id: 'stockx',
    name: 'StockX & Collectibles Radar',
    domain: 'commerce',
    description: 'Sneaker and collectible market tracking with historical peak alerts',
    tools: ['stockx_get_ticker', 'stockx_alert_spread'],
    samplePrompt: 'Check current market ask vs bid spread for Jordan 1 Retro Highs.',
  },
  {
    id: 'cashback',
    name: 'Affiliate Cashback Injector',
    domain: 'commerce',
    description: 'Affiliate network link generation and passive cashback monitoring',
    tools: ['cashback_get_link', 'cashback_audit_savings'],
    samplePrompt: 'Find the highest cashback or affiliate discount link for an upcoming office hardware purchase.',
  },
  {
    id: 'dropship',
    name: 'AliExpress & CJ Dropshipping',
    domain: 'commerce',
    description: 'Zero-touch order routing and tracking update bridge for e-commerce',
    tools: ['dropship_fulfill_order', 'dropship_track_carrier'],
    samplePrompt: 'Route pending store orders to the supplier API and synchronize tracking numbers.',
  },
  {
    id: 'shipstation',
    name: 'ShipStation & Logistics Hub',
    domain: 'commerce',
    description: 'Shipping label generation, carrier rate shopping, and parcel tracking',
    tools: ['shipping_rate_shop', 'shipping_print_label'],
    envKey: 'SHIPSTATION_API_KEY',
    samplePrompt: 'Compare shipping rates across USPS, UPS, and FedEx for a 3lb parcel to New York.',
  },

  // --- Domain III: Financial Autonomy (20) ---
  {
    id: 'crypto-portfolio',
    name: 'DeFi & Exchange Portfolio',
    domain: 'finance',
    description: 'Binance/Coinbase portfolio balance aggregation and gas optimization',
    tools: ['crypto_get_balances', 'crypto_simulate_swap'],
    envKey: 'COINBASE_API_KEY',
    samplePrompt: 'Retrieve current balances across exchanges and calculate optimal rebalancing transfers.',
  },
  {
    id: 'stock-brokerage',
    name: 'Alpaca Equities & DCA Engine',
    domain: 'finance',
    description: 'Algorithmic equity trading API, dividend reinvestment, and portfolio rebalancing',
    tools: ['alpaca_get_positions', 'alpaca_place_order'],
    envKey: 'APCA_API_SECRET_KEY',
    samplePrompt: 'Check current portfolio allocations against target ETF weightings.',
  },
  {
    id: 'real-estate',
    name: 'Zillow & Real Estate Valuation',
    domain: 'finance',
    description: 'Property value tracking, rental yield estimation, and mortgage rate monitoring',
    tools: ['re_get_property_estimate', 're_calc_cash_flow'],
    samplePrompt: 'Estimate cap rate and monthly cash flow for a rental property listing.',
  },
  {
    id: 'invoice-billing',
    name: 'Stripe & Automated Invoicing',
    domain: 'finance',
    description: 'Stripe, PayPal, and QuickBooks invoice generation and tax tracking',
    tools: ['stripe_create_invoice', 'stripe_track_payouts'],
    envKey: 'STRIPE_SECRET_KEY',
    samplePrompt: 'Generate a consulting invoice for 40 hours of development and send a payment link.',
  },
  {
    id: 'cloud-cost',
    name: 'AWS & Cloud Cost Guardrail',
    domain: 'finance',
    description: 'AWS, GCP, and Cloudflare spending anomaly detection and instance rightsizing',
    tools: ['cloud_cost_audit', 'cloud_cost_anomalies'],
    samplePrompt: 'Inspect AWS monthly billing run rate and highlight unattached EBS volumes.',
  },
  {
    id: 'ethereum-rpc',
    name: 'Ethereum & Arbitrum JSON-RPC',
    domain: 'finance',
    description: 'Smart contract interaction, gas estimation, and on-chain event subscriptions',
    tools: ['eth_get_block_number', 'eth_call_contract'],
    samplePrompt: 'Query the current base fee and gas priority fees on Ethereum mainnet.',
  },

  // --- Domain IV: Enterprise DevOps (20) ---
  {
    id: 'github-org',
    name: 'GitHub Enterprise & PR Triage',
    domain: 'devops',
    description: 'PR review assignment, automated release notes generation, and CI status checks',
    tools: ['gh_triage_prs', 'gh_create_release'],
    envKey: 'GITHUB_TOKEN',
    samplePrompt: 'Draft changelog release notes from merged PRs since the last tagged release.',
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty & Incident Commander',
    domain: 'devops',
    description: 'On-call escalation, incident summarization, and root-cause analysis',
    tools: ['pd_list_incidents', 'pd_acknowledge'],
    envKey: 'PAGERDUTY_API_KEY',
    samplePrompt: 'List all active PagerDuty incidents and provide an executive impact summary.',
  },
  {
    id: 'sentry-datadog',
    name: 'Sentry & APM Error Radar',
    domain: 'devops',
    description: 'Exception clustering, stack trace explanation, and regression alerts',
    tools: ['sentry_get_top_issues', 'datadog_query_metrics'],
    envKey: 'SENTRY_AUTH_TOKEN',
    samplePrompt: 'Fetch top unresolved Sentry errors from the last 24 hours with stack analysis.',
  },
  {
    id: 'docker-k8s',
    name: 'Kubernetes & Docker Fleet',
    domain: 'devops',
    description: 'Pod crash-loop diagnostics, container log streaming, and deployment rolling updates',
    tools: ['k8s_get_pods', 'k8s_describe_pod'],
    samplePrompt: 'Check for CrashLoopBackOff pods across all production namespaces and extract logs.',
  },

  // --- Domain V: Growth Marketing (20) ---
  {
    id: 'social-scheduler',
    name: 'Buffer & Social Media Auto-Pilot',
    domain: 'marketing',
    description: 'X/LinkedIn scheduled posting, thread generation, and engagement analytics',
    tools: ['social_schedule_post', 'social_get_analytics'],
    envKey: 'BUFFER_ACCESS_TOKEN',
    samplePrompt: 'Draft a 5-tweet educational thread on local LLM harness architectures and schedule it.',
  },
  {
    id: 'newsletter-growth',
    name: 'Substack & Beehiiv Engine',
    domain: 'marketing',
    description: 'Newsletter draft compilation, subscriber growth tracking, and open rate analysis',
    tools: ['newsletter_draft', 'newsletter_stats'],
    envKey: 'BEEHIIV_API_KEY',
    samplePrompt: 'Analyze open rates on our last three newsletter editions and generate topic ideas.',
  },
  {
    id: 'lead-gen',
    name: 'Apollo & B2B Prospecting',
    domain: 'marketing',
    description: 'Lead generation filter, email verification, and personalized cold outreach',
    tools: ['lead_search_companies', 'lead_verify_email'],
    envKey: 'APOLLO_API_KEY',
    samplePrompt: 'Find VP of Engineering prospects at series-A AI startups and draft tailored outreach.',
  },

  // --- Domain VI: AI & Multimodal Infra (20) ---
  {
    id: 'brave-search',
    name: 'Brave Search & Web Grounding',
    domain: 'ai',
    description: 'Real-time web search grounding, news queries, and link extraction',
    tools: ['brave_search', 'brave_news'],
    envKey: 'BRAVE_SEARCH_API_KEY',
    samplePrompt: 'Search for recent architectural breakthroughs in small language model reasoning.',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl Clean Markdown Extractor',
    domain: 'ai',
    description: 'Web crawler converting documentation sites into clean markdown for RAG',
    tools: ['firecrawl_scrape_page', 'firecrawl_crawl_site'],
    envKey: 'FIRECRAWL_API_KEY',
    samplePrompt: 'Scrape and extract clean markdown from the latest Cordis documentation site.',
  },
  {
    id: 'pinecone-vector',
    name: 'Pinecone Vector Semantic Memory',
    domain: 'ai',
    description: 'Long-term vector database storage, semantic clustering, and hybrid search',
    tools: ['vector_upsert_embeddings', 'vector_query_nearest'],
    envKey: 'PINECONE_API_KEY',
    samplePrompt: 'Query our vector index for the top 5 relevant code snippets matching memory compaction.',
  },

  // --- Domain VII: Creative Endeavors (20) ---
  {
    id: 'ableton-midi',
    name: 'Ableton Live & Generative MIDI',
    domain: 'creative',
    description: 'DAW MIDI API integration for generative composition, chord progressions, and stems',
    tools: ['ableton_generate_progression', 'ableton_trigger_clip'],
    samplePrompt: 'Generate a Neo-Soul chord progression in C Minor with 7th and 9th chord extensions.',
  },
  {
    id: 'blender-3d',
    name: 'Blender Procedural 3D Asset Studio',
    domain: 'creative',
    description: 'Blender Python script generator for procedural geometry, materials, and rendering',
    tools: ['blender_run_script', 'blender_render_frame'],
    samplePrompt: 'Write a Blender Python script to generate a low-poly procedural isometric room.',
  },
  {
    id: 'figma-design',
    name: 'Figma Token & UI Component Sync',
    domain: 'creative',
    description: 'Design system token extractor and automated SVG component generator',
    tools: ['figma_get_tokens', 'figma_export_svg'],
    envKey: 'FIGMA_PERSONAL_TOKEN',
    samplePrompt: 'Extract color and spacing design tokens from our Figma UI kit.',
  },
  {
    id: 'scrivener-novel',
    name: 'Scrivener Story & Lore Arc Engine',
    domain: 'creative',
    description: 'Manuscript chapter outliner, character consistency validator, and scene polisher',
    tools: ['novel_analyze_character_arcs', 'novel_draft_scene'],
    samplePrompt: 'Check character dialogue consistency in chapter 4 against their backstory profile.',
  },
  {
    id: 'unity-unreal',
    name: 'Unity & Unreal Level Prototyper',
    domain: 'creative',
    description: 'Game engine CLI script runner for blockout level assembly and physics testing',
    tools: ['engine_generate_level_layout', 'engine_build_prototype'],
    samplePrompt: 'Generate a C# Unity script for a modular dungeon room spawner with door sockets.',
  },
  {
    id: 'runway-video',
    name: 'Runway & AI Video Director',
    domain: 'creative',
    description: 'Script-to-storyboard generation, scene pacing, and video model prompt optimization',
    tools: ['video_generate_storyboard', 'video_render_clip'],
    envKey: 'RUNWAY_API_KEY',
    samplePrompt: 'Draft a visual storyboard and prompt parameters for a 15-second cinematic product teaser.',
  },
  {
    id: 'suno-audio',
    name: 'Suno AI Music Production Hub',
    domain: 'creative',
    description: 'Full-song lyric and style generation with stem separation and arrangement tags',
    tools: ['suno_generate_song', 'suno_separate_stems'],
    samplePrompt: 'Compose lyrics and production tags for a Synthwave instrumental track with retro arps.',
  },
]
